"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
import os
import dj_database_url

# =========================
# RUTAS BASE Y MEDIA
# =========================
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# =========================
# DEBUG & SECRET KEY
# =========================
# ⚠️ En Render pon DEBUG=False en las variables de entorno
SECRET_KEY = 'django-insecure-^%h2o!*pokg4#bqc_i!o(3@23!+@*bh@r6v&6dt$)_$60u_+it'
DEBUG = os.getenv("DEBUG", "True") == "True"

# En desarrollo aceptamos todo. En producción puedes afinar esto.
ALLOWED_HOSTS = ["*"]

# =========================
# USUARIO PERSONALIZADO
# =========================
AUTH_USER_MODEL = "cuentas.Usuario"

LOGIN_URL = "/cuentas/login/"
LOGIN_REDIRECT_URL = "/calificaciones/"
LOGOUT_REDIRECT_URL = "/cuentas/login/"

# =========================
# APLICACIONES
# =========================
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "cuentas.apps.CuentasConfig",
    "tributaria",
]

# =========================
# MIDDLEWARE
# =========================
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

# =========================
# TEMPLATES
# =========================
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# =========================
# BASE DE DATOS
# =========================
# 🔹 Por defecto: MySQL local (HeidiSQL)

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "nuam_sistema_tributario",  # el nombre que usas en Heidi
        "USER": "root",
        "PASSWORD": "admin",
        "HOST": "127.0.0.1",
        "PORT": "3306",
        "OPTIONS": {
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}

# 🔹 Si estamos en Render (DEBUG=False) y existe DATABASE_URL → usar PostgreSQL
DATABASE_URL = os.getenv("DATABASE_URL")

if DATABASE_URL:
    DATABASES["default"] = dj_database_url.config(
        default=DATABASE_URL,
        conn_max_age=600,
        ssl_require=True,
    )

# =========================
# VALIDACIÓN DE PASSWORD
# =========================
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# =========================
# INTERNACIONALIZACIÓN
# =========================
LANGUAGE_CODE = "es-cl"
TIME_ZONE = "America/Santiago"

USE_I18N = True
USE_TZ = True  # Puedes dejar True, Django guarda en UTC pero muestra en tu zona

# =========================
# STATICFILES
# =========================
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# ⚠️ Para que no te salga el warning, crea la carpeta:
#   C:\Users\xboxm\Downloads\NUAM\config\static
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Whitenoise para servir estáticos en Render
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# =========================
# DEFAULT PRIMARY KEY
# =========================
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

