# Generated by Django 5.2.7 on 2025-11-14 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('rut', models.CharField(max_length=20)),
                ('email_contacto', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoTributario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_archivo', models.CharField(choices=[('CSV', 'CSV'), ('XLSX', 'Excel'), ('XML', 'XML'), ('PDF', 'PDF (certificado)')], max_length=10)),
                ('archivo', models.FileField(upload_to='archivos_tributarios/')),
                ('nombre_original', models.CharField(max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='PENDIENTE', max_length=20)),
                ('mensaje_estado', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('emisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tributaria.emisor')),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=255)),
                ('entidad', models.CharField(max_length=100)),
                ('id_registro', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalle', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corredor', models.CharField(max_length=100)),
                ('instrumento', models.CharField(blank=True, max_length=100)),
                ('anio_tributario', models.IntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('factor', models.DecimalField(decimal_places=5, max_digits=10)),
                ('monto_calificado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fuente', models.CharField(help_text='Por ejemplo: DJ, Certificado Emisor', max_length=50)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('VALIDADA', 'Validada'), ('PUBLICADA', 'Publicada')], default='BORRADOR', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('archivo_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tributaria.archivotributario')),
                ('usuario_responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tributaria.emisor')),
            ],
        ),
        migrations.CreateModel(
            name='ErrorValidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.IntegerField()),
                ('campo', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('nivel', models.CharField(default='ERROR', max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errores', to='tributaria.archivotributario')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
