# Generated by Django 5.2.7 on 2025-11-28 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errorvalidacion',
            options={'verbose_name': 'Error de validación', 'verbose_name_plural': 'Errores de validación'},
        ),
        migrations.RenameField(
            model_name='errorvalidacion',
            old_name='fila',
            new_name='nro_linea',
        ),
        migrations.RemoveField(
            model_name='errorvalidacion',
            name='campo',
        ),
        migrations.RemoveField(
            model_name='errorvalidacion',
            name='nivel',
        ),
        migrations.AddField(
            model_name='errorvalidacion',
            name='calificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errores_validacion', to='tributaria.calificaciontributaria'),
        ),
        migrations.AlterField(
            model_name='errorvalidacion',
            name='archivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errores_validacion', to='tributaria.archivotributario'),
        ),
    ]
