# Generated by Django 5.2.7 on 2025-11-28 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributaria', '0002_alter_errorvalidacion_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacion',
            old_name='fecha_creacion',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='titulo',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='nivel',
            field=models.CharField(choices=[('INFO', 'Información'), ('WARNING', 'Advertencia'), ('ERROR', 'Error')], default='INFO', max_length=10),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='mensaje',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
