# Generated by Django 5.2.7 on 2025-12-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributaria', '0004_documentopdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentopdf',
            name='anio_tributario',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentopdf',
            name='estado',
            field=models.CharField(blank=True, default='PENDIENTE', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='documentopdf',
            name='factor',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='documentopdf',
            name='monto_bruto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='documentopdf',
            name='nombre_emisor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='documentopdf',
            name='rut_emisor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
